Update check_required_files.yml

diff --git a/.github/workflows/check_required_files.yml b/.github/workflows/check_required_files.yml
--- a/.github/workflows/check_required_files.yml
+++ b/.github/workflows/check_required_files.yml
@@ -1,7 +1,8 @@
-## Check required files exist
-# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
+# This worklow will check for the presence of README.md and .gitignore files.
+# Then install Python dependencies, run tests and lint with a variety of Python versions.
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python package
+name: TestsPackage
 
 on:
   push:
@@ -16,26 +17,47 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        check required files exist: ["Check required files"]
-#        test: ["Check required files exist"]
+        python-version: ["3.9", "3.10", "3.11"]
 
     steps:
     - uses: actions/checkout@v4
-    
+
+    - name: Check presence of README.md
+      run: |
+        if [ ! -f "README.md" ]; then
+          echo "ERROR: README.md not found!"
+          exit 1
+        else
+          echo "README.md exists."
+        fi
+
+    - name: Check presence of .gitignore
+      run: |
+        if [ ! -f ".gitignore" ]; then
+          echo "ERROR: .gitignore not found!"
+          exit 1
+        else
+          echo ".gitignore exists."
+        fi
+
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
-        python-version: ${{ matrix.check_required_files }}
+        python-version: ${{ matrix.python-version }}
 
-    - name: Check required files
+    - name: Install dependencies
       run: |
-        if [ ! -f "README.md", ".gitignore" ]; then
-            echo "ERROR: README.md not found!"
-            exit 1
-        else
-            echo "README.md exists."
-        fi 
-    - name: Check required files exist
+        python -m pip install --upgrade pip
+        python -m pip install flake8 pytest
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+    - name: Lint with flake8
+      run: |
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Test with pytest
       run: |
         pytest tests/
-        
